spring:
  application:
    name: UserLogin
  datasource:
    username: root
    password: ndwmd1230
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.54.125:3306/Campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
server:
  servlet:
    context-path: /tcu

  port: 9090
